meta_product_name: "Foodies"

meta_title: "Foodies – Eating with friends!"

meta_description: "A social network dedicated entirely to sharing food experiences through users' original recipes and restaurant visits around the world"

meta_image: "cover.png" # should exist in `app/assets/images/`
